services:
  redis:
    image: redis:7-alpine
    container_name: opspulse-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - opspulse-net

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: opspulse-timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opspulse
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - opspulse-net

volumes:
  redis_data:
  timescale_data:

networks:
  opspulse-net:
    driver: bridge
